role: workstation
git:
  repo: https://github.com/YOURUSER/YOURREPO.git
  branch: main
  allowlist:
    - abcdef1234567890deadbeefdeadbeefdeadbeef  # trusted commit hashes
buckets:
  - extras
  - nerd-fonts
apps:
  required:
    - python
    - 7zip
    - git
    - curl
    - vim
    - sysinternals
    - sudo
    - jq
    - nmap
  optional:
    - ffmpeg
    - vlc
services:
  # Use the service Name from Get-Service for each entry
  # Lists under each role can contain multiple service names
  workstation:
    disable:
      - DiagTrack
      - OneSyncSvc
      - XblAuthManager
      # Add more services here, e.g. RemoteRegistry
    enable:
      - WSearch
  server:
    disable:
      - PrintSpooler
      - Fax
      # Add more services here, e.g. AppMgmt
firewall:
  trusted_subnet: auto
  block_telemetry: true
  detailed_diff: true
